### ISSUE TITLE
(flatpak) can't turn "save changes to files" on

### ISSUE THREAD

**Issue by legacychimera247** [gnumdk/lollypop#1241]
as the title say i cannot turn on the save to files option...i can turn it on but it will not work and if i reopen the settings panel that option is still turned off...maybe it's related to the changes you made in [https://github.com/gnumdk/lollypop/issues/1223](url) ?

**Comment by bil-elmoussaoui** [comment]
It's due to a missing dependency on the flatpak package https://github.com/flathub/org.gnome.Lollypop/blob/master/org.gnome.Lollypop.json
It must be kid3

**Comment by gnumdk** [comment]
No, Lollypop is using a portal to communicate with kid3-cli from system. Will give a look soon.

**Comment by gnumdk** [comment]
I think this one is already fixed. I tried, get an error but I know this code is not present in master.

**Comment by gnumdk** [comment]
@legacychimera247 Does it work now?

**Comment by legacychimera247** [comment]
nope...the error is not fixed...i can turn it on but if i return back to the menu is still off...and retrieving cover arts is still not working btw...

**Comment by gnumdk** [comment]
Are you sure lollypop-portal is installed?

**Comment by legacychimera247** [comment]
checked...portal is installed...

**Comment by gnumdk** [comment]
Strange, here it works... Nothing on command line?

**Comment by legacychimera247** [comment]
if i open settings and turn save changes to file on here's what i get

`DBusHelper::__on_get_proxy(): g-dbus-error-quark: Errore nel chiamare StartServiceByName per org.gnome.Lollypop.Portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Lollypop.Portal received signal 5 (26)
DBusHelper::__on_get_proxy(): g-dbus-error-quark: Errore nel chiamare StartServiceByName per org.gnome.Lollypop.Portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Lollypop.Portal received signal 5 (26)`

**Comment by gnumdk** [comment]
please run lollypop with LANG=C

**Comment by gnumdk** [comment]
What I see is that portal is not installed...

**Comment by legacychimera247** [comment]
well if i open the gnome package manager and search for lollypop i get that the lollypop portal package is already installed and i can only remove it...maybe you have a terminal command for installing it?

**Comment by gnumdk** [comment]
Distro?

**Comment by legacychimera247** [comment]
fedora workstation 26

**Comment by gnumdk** [comment]
So the lollypop-portal package comes from Fedora...

**Comment by gnumdk** [comment]
Will give a look on F27

**Comment by gnumdk** [comment]
Tested, flatpak lollypop + fedora lollypop-portal, all is ok...

\# dnf remove lollypop-portal
\# dnf install lollypop-portal

**Comment by legacychimera247** [comment]
done but nope, the error is still there...maybe i can just switch for the rpm version for now?

**Comment by legacychimera247** [comment]
anyway if the right command is `flatpak run org.gnome.Lollypop/x86_64/stable LANG=C` or lang=c then it simply does nothing...the app opens up as always (in italian) and can't turn this option on...

**Comment by gnumdk** [comment]
\$ ls -l /usr/share/dbus-1/services/org.gnome.Lollypop.Portal.service
\$ ls -l /usr/libexec/lollypop-portal

And more important, be sure you do not have Lollypop portal files in /usr/local

**Comment by gnumdk** [comment]
> Process org.gnome.Lollypop.Portal received signal 5 

You can also try to run  /usr/libexec/lollypop-portal and see if it is failing

**Comment by legacychimera247** [comment]
first 2 commands
`[luca247@localhost ~]$ ls -l /usr/share/dbus-1/services/org.gnome.Lollypop.Portal.service
-rw-r--r--. 1 root root 81 27 lug 08.56 /usr/share/dbus-1/services/org.gnome.Lollypop.Portal.service
[luca247@localhost ~]$ ls -l /usr/libexec/lollypop-portal
-rwxr-xr-x. 1 root root 7031 27 lug 08.56 /usr/libexec/lollypop-portal
`

second commands gives me an error saying lollypop portal is not installed (while it is)

**Comment by gnumdk** [comment]
>second command gives me an error saying lollypop portal is not installed (while it is)

What is the exact message?

**Comment by legacychimera247** [comment]
that's the message

`(python3:2334): GLib-GIO-ERROR **: Settings schema 'org.gnome.Lollypop' is not installed

Trace/breakpoint trap (created dump core)
`

**Comment by gnumdk** [comment]
Oh shit :-1:
I know what is wrong but have no idea how to fix it without removing "tag-editor" dconf key :-/

**Comment by gnumdk** [comment]
Fixed, rpm update in my copr.

**Comment by legacychimera247** [comment]
ok but i was using the flatpak...the rpm was already working fine...anyway i downloaded the lollyportal update and now it keeps crashing all the times...

**Comment by legacychimera247** [comment]
the usual one

`DBusHelper::__on_get_proxy(): g-dbus-error-quark: Errore nel chiamare StartServiceByName per org.gnome.Lollypop.Portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Lollypop.Portal received signal 5 (26)
DBusHelper::__on_get_proxy(): g-dbus-error-quark: Errore nel chiamare StartServiceByName per org.gnome.Lollypop.Portal: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process org.gnome.Lollypop.Portal received signal 5 (26)`

**Comment by gnumdk** [comment]
Not this one, when you run lollypop-portal on command line

**Comment by gnumdk** [comment]
@legacychimera247 ?

**Comment by legacychimera247** [comment]
sorry for the late reply...anyway if i run that command from the command line i get a command not found message...

**Comment by gnumdk** [comment]
/usr/libexec/lollypop-portal ;)

**Comment by legacychimera247** [comment]
yeah, sorry...

`(python3:9758): GLib-GIO-ERROR **: Settings schema 'org.gnome.Lollypop' is not installed

Trace/breakpoint trap (core dump created)
`

**Comment by gnumdk** [comment]
>anyway i downloaded the lollyportal update

Seems you did not...

**Comment by gnumdk** [comment]
rpm -q lollypop-portal

**Comment by legacychimera247** [comment]
well if i input sudo dnf install -y lollypop-portal, terminal says package is already installed, and org.gnome.Lollypop/x86_64/stable is in the configured remotes list...something else i should check/do?

**Comment by legacychimera247** [comment]
your command results in `lollypop-portal-0.9.303-1.fc26.noarch`

**Comment by gnumdk** [comment]
So your are not using my COPR... And 0.9.304 is in testing...

**Comment by gnumdk** [comment]
https://pkgs.org/download/lollypop-portal

**Comment by legacychimera247** [comment]
well i simply went to the flathub store and downloaded lollypop from there in flatpak, the since lollypop portal was evidently missing i've installed it via the dnf install lollypop-portal command...maybe this version is only suitable  for fedora's packaged version?i need to use your copr to have a working version?

**Comment by gnumdk** [comment]
Just download the package from testing, update will move soon to normal updates.

**Comment by legacychimera247** [comment]
just set your copr and updated via terminal...problem solved now :)

**Comment by legacychimera247** [comment]
on the side note of it, changing or deleting the artwork has no effect at all...

**Comment by gnumdk** [comment]
Any message on both command line?
kill lollypop-portal, run it on command line
run lollypop on command line

**Comment by legacychimera247** [comment]
so...this is the message while changing artwork
`(lollypop:2): Gtk-CRITICAL **: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
TaskHelper::__on_soup_msg_finished(): g-io-error-quark: L'operazione è stata annullata (19)`

this is the one while deleting an artwork
`(lollypop:2): Gtk-CRITICAL **: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
TaskHelper::__on_read_bytes_async(): g-io-error-quark: L'operazione è stata annullata (19)`

and this is the one by running lollypop portal
`Failed to register: Unable to acquire bus name 'org.gnome.Lollypop.Portal'`

**Comment by gnumdk** [comment]
Ok, I need Lollypop portal messages:

You did not kill portal if you have this message:
Failed to register: Unable to acquire bus name 'org.gnome.Lollypop.Portal'

**Comment by legacychimera247** [comment]
think you should remind me how to kill lollypop-portal...i tried in killing it all of the processes but everytime there's a process that change pid continuosly and anyway the commenad for run lollypop simply does nothing...it just open the process that can only be killed...i used `kill -9 pid` to kill various process...maybe it's something else?

**Comment by d9h20f** [comment]
You can use pkill to kill a process by name (much easier).

**Comment by legacychimera247** [comment]
tried it with pkill lollypop-portal but still i don't get any result...

**Comment by gnumdk** [comment]
Close lollypop before killing it...

**Comment by gnumdk** [comment]
[gnumdk@arch ~]$ ps ax|grep lollypop-portal
14222 ?        Sl     0:00 python3 /usr/local/libexec/lollypop-portal
16220 pts/1    S+     0:00 grep lollypop-portal
[gnumdk@arch ~]$ kill 14222
[gnumdk@arch ~]$ ps ax|grep lollypop-portal
16222 pts/1    S+     0:00 grep lollypop-portal

**Comment by legacychimera247** [comment]
lollypop was closed without opening it at firs...will try anyway...

**Comment by legacychimera247** [comment]
now i only get

`2097 pts/0    S+     0:00 grep --color=auto lollypop-portal` and seems that the pid varies everytime...

**Comment by gnumdk** [comment]
So launch the command from cmdline now it's killed

**Comment by legacychimera247** [comment]
sorry but...if the command is `/usr/libexec/lollypop-portal` i've already told multiple times that i have no results at all in cmd...i just get the currsor in terminal flashing (waiting for something) and it stays like this forever...and by the way the lollypop-portal process is turned on...

**Comment by gnumdk** [comment]
It's normal but do you have output when you set a cover?

**Comment by gnumdk** [comment]
Next question if no output:
- Does the folder contains a folder.jpg cover?
- Does the files tags get updated?

**Comment by legacychimera247** [comment]
if you are talking about lollypop-portal and the `/usr/libexec/lollypop-portal` command then no, i don't get any results while changing artwork...if you are talking about lollypop when `/usr/libexec/lollypop-portal` is running in terminal the result i get while changing artwork is `(lollypop:2): Gtk-CRITICAL **: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
TaskHelper::__on_soup_msg_finished(): g-io-error-quark: operation was cancelled (19)`

if you questions are related to the cover i am trying to change then no, i don't have any jpeg in folder and tags get correctly updated...

**Comment by gnumdk** [comment]
So cache is not correctly cleaned.
