### ISSUE TITLE
F22 python

### ISSUE THREAD

**Issue by ballinger** [gnumdk/lollypop#171]
hi, you told me already that fedora 22 doesnt have pylast, but i was stubborn and tried it anyway.
python3.4 -m pip install pylast
python3.4 -m pip install wikipedia

which actually works if lollypop starts building the library from scratch. the artist info is fetched from wikipedia and all is fine until i restart lollypop. starting it the second time gives me an error. any ideas?

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 572, in _on_list_one_selected
    self._update_view_artists(selected_id, None)
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 429, in _update_view_artists
    view = ArtistView(artist_id, genre_id)
  File "/usr/local/lib/python3.4/site-packages/lollypop/view_albums.py", line 38, in __init__
    self._artist_name = Lp.artists.get_name(artist_id)
  File "/usr/local/lib/python3.4/site-packages/lollypop/database_artists.py", line 66, in get_name
    (artist_id,))
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139968596576000 and this is thread id 139967904810752
Exception ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 1297, in _shutdown
    _main_thread._delete()
  File "/usr/lib64/python3.4/threading.py", line 1020, in _delete
    del _active[get_ident()]
KeyError: 139967904810752

**Comment by gnumdk** [comment]
No idea, this function should no be runned outside main thread.. Really strange behaviour, do you do some action before crash?

**Comment by gnumdk** [comment]
No crash if you remove wikipedia and lastfm?

**Comment by ballinger** [comment]
i was messing around with pylast and wikipedia linking them from 2.7 to the 3.4 folder which kinda worked but removed those links after i found the "official" way (python3.4 -m pip install pylast) i removed both python modules with python3.4 -m pip uninstall pylast wikipedia. searching for them in lib and lib64 doesnt give any results anymore. i also did a dnf reinstall python3 which didnt help. guess i messed something up with my noobism. ill play around with it a little more, i really like this music player, it is a joy scrolling through a library with album covers and not text entries. the only thing i am missing is a way to enlarge the cover album somehow, maybe even some way to flip through all the pics in the album folder. i will let u know if i find a way for the python madness.

**Comment by gnumdk** [comment]
I'm using Fedora 22 as main system and install it with:
#pip3 install pylast

**Comment by gnumdk** [comment]
Should be fixed

**Comment by ballinger** [comment]
hey, nice to know you have my prob in mind :) but it didn't quite fix the problem. think its a problem on my side since lollypop was running beautifully the longest time. think ill just reinstall f22 from scratch since i have no clue what i messed up.
lollypop
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/view.py", line 109, in _on_current_changed
    GLib.idle_add(self._update_widgets, self._get_children(), False)
  File "/usr/local/lib/python3.4/site-packages/lollypop/view_albums.py", line 97, in _get_children
    return self._albumbox.get_children()
AttributeError: 'ArtistView' object has no attribute '_albumbox'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 572, in _on_list_one_selected
    self._update_view_artists(selected_id, None)
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 429, in _update_view_artists
    view = ArtistView(artist_id, genre_id)
  File "/usr/local/lib/python3.4/site-packages/lollypop/view_albums.py", line 38, in __init__
    self._artist_name = Lp.artists.get_name(artist_id)
  File "/usr/local/lib/python3.4/site-packages/lollypop/database_artists.py", line 66, in get_name
    (artist_id,))
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139921066018560 and this is thread id 139920491173632
Exception ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 1297, in _shutdown
    _main_thread._delete()
  File "/usr/lib64/python3.4/threading.py", line 1020, in _delete
    del _active[get_ident()]
KeyError: 139920491173632

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 32577 and height -12

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 32577 and height -12

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 0 and height -12

(lollypop:15754): Gtk-CRITICAL **: gtk_widget_get_preferred_width_for_height: assertion 'height >= 0' failed

(lollypop:15754): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -955376511 and height -12

**Comment by ballinger** [comment]
just wanted to let you know that all is working again.(including pylast, wikipedia) something was messed up on my system... was originally installed from f22 alpha. keep up the great work. lollypop rocks!
