### ISSUE TITLE
Album art appears too big and with a wrong aspect ratio under Wayland

### ISSUE THREAD

**Issue by michael-rapp** [gnumdk/lollypop#582]
-Lollypop version: 0.9.96
-Gtk Version: 3.20.3
-Linux distribution: Arch Linux

When GNOME 3.20 was released recently, I switched from running it under a traditional X session to using Wayland as the display server. Since then the cover artworks in Lollypop are displayed way too big and with a wrong aspect ratio as you can see it on the attached screenshot. When I switch back to X everything looks like it used to. 

Propably this issue is affected by the hidpi screen of my laptop (the resolution is 2880 x 1620), which requires all windows to be scaled up to twice their original size. When I started Lollypop on an external monitor, which does not require window scaling, the album covers were first displayed faulty as well, but when I changed the album cover size in the settings, the issue dissapeared. On the hidpi screen changing the album cover size doesn't  cause the problems to go away.

Edit: When I took a closer look, I realized that the aspect ratio of the pictures seems to be fine. What's causing the cover arts to appear rectangular instead of squared is, that they overlap each other because they're too big. By the way, the covers displayed in the search and in the title bar when playing music are also too big. So it seems like an wrong album cover size is calculated in general.

![screenshot from 2016-04-21 13-59-31](https://cloud.githubusercontent.com/assets/6638695/14708278/13367c1c-07ca-11e6-8a32-95a1e7012a31.png)

**Comment by gnumdk** [comment]
Here on Fedora and GTK 3.18, HiDPI is not working on Wayland, is this new in GNOME 3.20?

**Comment by gnumdk** [comment]
Seems we can't force HiDPI on wayland :-(

**Comment by gnumdk** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=765421

**Comment by gnumdk** [comment]
Can you save this to a file

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GdkPixbuf, Gdk

image = Gtk.Image()
pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size("/usr/share/icons/Adwaita/256x256/apps/web-browser.png", 100*image.get_scale_factor(), 100*image.get_scale_factor())
surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, 0, None)
image.set_from_surface(surface)
win = Gtk.Window()
win.connect("delete-event", Gtk.main_quit)
win.add(image)
win.show_all()
Gtk.main()
```
Can you run this in your wayland session, does the image appear as 100x100 or 200x200 px?

**Comment by gnumdk** [comment]
Once you get the value, replace:
surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, 0, None)
by:
surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, 0, image.get_window())

**Comment by michael-rapp** [comment]
On GNOME 3.20 hidpi support works out of the box. The scale factors for each monitor are applied fully automatically. Manually setting a scale factor, e.g. by using the Gnome Tweak Tool, does not have an effect anymore.

I ran the code sample you gave me (on the hipdi screen and under Wayland of course) and the output looks like follows. The image has a size of 400x400px.

![screenshot from 2016-04-22 14-16-27](https://cloud.githubusercontent.com/assets/6638695/14741209/f148c6de-0894-11e6-8820-2c709d275731.png)

Then I changed the line to `surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, 0, image.get_window())`, but the output remained exactly the same.

**Comment by gnumdk** [comment]
And if you put this:
surface = Gdk.cairo_surface_create_from_pixbuf(pixbuf, 2, None)

I assume the scale factor is 2

**Comment by michael-rapp** [comment]
Then the image seems to be properly sized.

![screenshot from 2016-04-22 14-28-48](https://cloud.githubusercontent.com/assets/6638695/14741494/d4b86b12-0896-11e6-9ebb-501f30823c6d.png)

**Comment by gnumdk** [comment]
So fixed by previous commit.

**Comment by gnumdk** [comment]
Can you test master? To be sure nothing is broken in HiDPI as previous commit changed a lot of code.

I can help you to build lollypop from git ;)

**Comment by michael-rapp** [comment]
Alright, I just built lollypop from git and tested it out. I (almost) could not find any album art being scaled incorrectly. Nice work!

The only thing, which still appears to be scaled incorrectly is the album cover shown in fullscreen mode. It looks like this: 

![screenshot from 2016-04-22 14-52-49](https://cloud.githubusercontent.com/assets/6638695/14742019/4de16748-089a-11e6-8d96-bbd776cb74a8.png)

**Comment by gnumdk** [comment]
In a python3 prompt, do this:
>>> screen = Gdk.Screen.get_default()
>>> monitor = screen.get_primary_monitor()
>>> geometry = screen.get_monitor_geometry(monitor)
>>> print(geometry.height, geometry.width)

**Comment by michael-rapp** [comment]
The output is: `1620 2880`

**Comment by gnumdk** [comment]
Ok, I know why, will fix it in the train ;)

**Comment by gnumdk** [comment]
Can you enable "Show artist artwork" and tell me if artist artwork is well sized ?

Thanks

**Comment by michael-rapp** [comment]
You can see it on the screenshot below. To me it looks alright, but I'm not sure if it actually is the correct size. Another think I just realized can be seen on the screenshot as well: When no album cover is available, the default image is still not sized correctly.

![screenshot from 2016-04-22 16-32-06](https://cloud.githubusercontent.com/assets/6638695/14744622/cc51025c-08a7-11e6-9378-d91c76b1381d.png)

**Comment by gnumdk** [comment]
Fixed

**Comment by gnumdk** [comment]
Tips: You have 2 "Origin" albums because:
- Not same album year for all tracks or
- Not same album artist for all tracks
;)

**Comment by michael-rapp** [comment]
I installed from master again and I can confirm that the default image now has the correct size and that the fullscreen mode now looks proper.

PS: Yeah my id3tags are screwed up to some extent :-D
